name: reathm
description: "A daily companion app for motivation and encouragement."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  provider: ^6.1.5
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0
  cloud_functions: ^6.0.0
  flutter_local_notifications: ^19.4.1
  timezone: ^0.10.1
  intl: ^0.19.0
  google_sign_in: 6.1.0
  package_info_plus: ^8.0.0
  table_calendar: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  fake_cloud_firestore: ^4.0.0
  firebase_core_platform_interface: ^6.0.0
  plugin_platform_interface: ^2.1.8
  firebase_auth_mocks: ^0.15.0
  

flutter:
  uses-material-design: true